---
title: "Beginning R - Summary"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Well done for getting this far! We've covered a lot in this course:

* RStudio (introduction)
* The `print()` function
* Basic data types: strings, logicals and numerics (floating point and integer)
* Indexing, subsetting and appending to vectors
* Looping over different vectors
* Branching logic using `if` statements
* Creating, modifying and accessing dictionaries and lookup tables
* Reading files

You're not expected to have committed all of this to memory already, 
learning any programming language takes more than three hours. It is 
only by continuing to use R and practise that you will become confident. 
These notes will remain online so feel free to refer back to them at any time.

> EXERCISE
>
> Let's end this session with a more difficult challenge. We're going to make 
> a calculator which can read numerical operations from a file and print the 
> answers to the screen.
>
> Start by making a file called `calc.txt` with the following contents:
>
> 4 * 6
>
> 5 + 6
> 
> 457 - 75
>
> 54 / 3
>
> 4 + 6
>
> Make sure that you have the spaces between each number and the operator.
>
> Write a program which reads in that file and performs the mathematical 
> operations listed. It should output something like:
>
> 4 * 6 is 24
> 
> 5 + 6 is 11
>
> 457 - 75 is 382
>
> 54 / 3 is 18.0
> 
> 4 + 6 is 10
>
> There are some extra functions that you may need;
>
> `strsplit(file_line, " ")` will split each line of text into a vector of 
> strings, using space as a delimiter and will return a list of these vectors.
>
> `cat(expression, "is", value, "\n")` will print values to the screen,
> while adding a newline onto the end of each line.
> 
> [Answer](summary_answer01.html)

This workshop has given you a beginning introduction on R as a programming
language. This, together with our [Intermediate R](https://chryswoods.com/intermediate_r)
should provide you with a firm foundation as you continue
to learn R and apply it for statistical programming and data science
applications.

If you'd like to learn more R take a look at this excellent book by 
Hadley Wickham:

* [Advanced R](https://adv-r.hadley.nz/index.html) - this book is a great way
to learn more about R as a programming language.
* [R for Data Science](https://r4ds.had.co.nz) - this book is a brilliant
introduction on how to use R for data science.
* [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) - if
you prefer to learn through practical exercises then this is a good place to start.

If you are interested in the philosophy and history of the language I would recommend:

* [The History of S](https://sas.uwaterloo.ca/~rwoldfor/software/R-code/historyOfS.pdf)
written by one of the original creators of the language.
* [An interview with John Chambers](https://www.youtube.com/watch?v=jk9S3RTAl38),
an original developer of S and part of the R core team.
* [Forty years of S](https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/Forty-years-of-S),
a talk given by Richard Becker, another of the original developers.

As you would expect R comes with its own comprehensive set of manuals, the
following are of most use to someone starting to learn R:

* [An Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.html)
* [R Language Definition](https://cran.r-project.org/doc/manuals/r-release/R-lang.html)
* [R Data Import/Export](https://cran.r-project.org/doc/manuals/r-release/R-data.html)

Once you have completed this workshop and [Intermediate R](https://chryswoods.com/intermediate_r),
you will be ready to take are future workshops, [Introduction to Data Analysis in R](https://chryswoods.com/data_analysis_r)
and "Applied Data Analysis in R". These will be linked here once they 
are ready.

We have mentioned conventions a number of times when describing the layout of code.
This is because when writing R code it is a good idea to keep a consistent syntax
style to aid other people reading it. The following guides cover some popular variants:

* [The Tidyverse Style Guide](https://style.tidyverse.org/syntax.html)
* [Google’s R Style Guide](https://google.github.io/styleguide/Rguide.html)

In various places in this module I have warned of traps to be avoided when writing 
in R and you can find a more comprehensive list of these in the short book [The R Inferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf). These are often due
to the power and flexibility of being a general purpose programming language and you
will find similar cases in nearly all languages (computer or human based). Do not let 
this put you off learning the language however as this just reinforces the importance
of testing what you write, and if possible having it reviewed by a second pair of eyes.
As you become more familiar with the language you should become better at spotting
and avoiding these.

## Credits

This "Beginning R" workshop closely mirrors our
[Beginning Python](https://milliams.com/courses/beginning_python) workshop,
which was developed by Matt Williams, based on an earlier
[Beginning Python](https://chryswoods.com/beginning_python) workshop written
by Christopher Woods.

All text is published under a 
[Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/) 
with all code snippets licensed as MIT.

The source for the material can be found on [GitHub](https://github.com/chryswoods/siremol.org/tree/master/chryswoods.com/beginning_r) 
where fixes are welcome.

## [Previous](files.html)
