---
title: "Text and Sentiment Analysis in R"
output:
  html_document:
    df_print: paged
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r}
library(tidyverse)
text_lines <- readLines("https://chryswoods.com/text_analysis_r/hamlet.txt")
hamlet <- tibble(line = seq_along(text_lines), text = text_lines)

hamlet %>% mutate(text = str_replace_all(text, 
                                       regex("\\bthe\\s\\w+", 
                                             ignore_case = TRUE), 
                                       "the banana"))
```

If you wanted to preserve the case of `The` then you would perform two
replacements, e.g.

```{r}
hamlet %>% 
    mutate(text = str_replace_all(text, 
                                  "\\bthe\\s\\w+", 
                                  "the banana")) %>%
    mutate(text = str_replace_all(text,
                                  "\\bThe\\s\\w+",
                                  "The banana"))
```


## [Return](regexp.html)

