---
title: "Intermediate R - Tidyverse"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As mentioned before, R is an old programming language that was written
as a re-implementation of the even older language, S. Computing environments
have evolved a lot over the years and a lot of assumptions regarding the available
computing facilities and types of analysis are no longer valid. As R is an open
extensible environment addon packages have been written independently by a huge
number of people, often motivated by their own research and therefore a lot of
inconsistencies in terminology and expected behaviour have emerged. This can be
confusing and can mean that code can sometimes not behave as its author expects.

As tens of thousands of packages, and many times more user written scripts rely
on the functions in base R it is impossible for these to be updated into a
consistent structure without breaking a lot of existing code. To solve this
problem the tidyverse packages were developed by Hadley Wickham, Chief Scientist
at RStudio. These build on the data structures that we have previously described
to provide replacements for the base R functions that are designed to
work together and behave in a consistent way and with a common philosophy.

I strongly recommend that if you are doing data analysis that you use the
tidyverse where possible when starting new work as this should greatly reduce
the scope for errors and make the scripts more readable. It is important however
to have some familiarly with the base R functions as much of the existing code
you encounter will use this and most packages outside of the tidyverse will be
written using base R. As the tidyverse is under active development some aspects
are considered experimental and are subject to change. It is therefore even more
important that you record the versions of the tidyverse packages that you use.

There is lots of information about the tidyverse on the web, e.g.

* [What is the tidyverse?](https://rviews.rstudio.com/2017/06/08/what-is-the-tidyverse/)
* [R for Data Science](https://r4ds.had.co.nz) - an online book by 
Garrett Grolemund and Hadley Wickham that teaches the concepts of 
tidy data and shows how R with the tidyverse will help you create
tidy data workflows.

## Loading the tidyverse

You can install and use the tidyverse by typing;

```R
install.packages("tidyverse")
library(tidyverse)
```

This will download and then import the tidyverse modules. You should
see something similar to this printed;

```
── Attaching packages ────────────────── tidyverse 1.3.0 ──
✓ ggplot2 3.3.2     ✓ purrr   0.3.4
✓ tibble  3.0.3     ✓ dplyr   1.0.2
✓ tidyr   1.1.2     ✓ forcats 0.5.0
✓ readr   1.3.1     
── Conflicts ───────────────────── tidyverse_conflicts() ──
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
```

This shows that the seven core tidyverse modules have been loaded
([ggplot2](https://ggplot2-book.org), [tibble](https://tibble.tidyverse.org),
[tidyr](https://tidyr.tidyverse.org), [readr](https://readr.tidyverse.org),
[purrr](https://purrr.tidyverse.org), [dplyr](https://dplyr.tidyverse.org)
and [forcats](https://forcats.tidyverse.org)).

It also shows how the modern `dplyr::filter` and `dplyr::lag`
functions mask the older `stats::filter` and `stats::lag` functions.
If for some reason you still need to use these functions you can still
call them using the `::` namespace syntax. The functions being masked
just means that if you omit the namespace you will get the `dplyr` version.

> EXERCISE
>
> Install and load the tidyverse. Use the links above for the seven
> modules to find out exactly what each package provides.
>
> [Answer](tidyverse_answer01.html)

## Tibbles and readr

We will learn and use the tidyverse in much more depth in future 
workshops. For today, we will look at `tibble`. A `tibble` is a modernised
variant of  the `data.frame` designed to work with the tidyverse. While you
might think that this would make them more complicated in fact the opposite is
true. The goal of the `tibble` was to remove any unexpected automatic behaviour
and to be a simple as possible. The authors describe this as being "lazy and surly",
i.e. they do less and complain more than the `data.frame` type on which they are
based.

In particular, compared with a `data.frame` they never change the names of
variables, they don't automatically coerce string to factors (base R changed
its behaviour to match this in version 4.0.0), they don't allow row names to
be specified and two dimensional indexing of a `tibble` always returns a new
`tibble` (equivalent to `drop = FALSE` in `data.frame`). The other change relating
to indexing is that the `tibble` no longer allows partial matching when using `$`
for indexing. This greatly reduces that chances that the wrong variable will be
selected.

The other major user-facing difference is when `tibble` is printed to the screen.
Rather than displaying all of the data it behaves like a combination of the `head`
and `str` functions, showing only the first few rows of data, along with their
data type.

As the `tibble` is simply an extension of the `data.frame` class most existing
functions and packages that work with `data.frame` will also work with `tibble`
(and vice versa) as long as they do not rely on any of the changed behaviour.
If you do find this to be a problem you can easily convert your data using
the `as.data.frame` or `as_tibble` functions.

In the same way, `readr` provides modern tidyverse replacements 
for R's standard reading functions. `readr` provides `read_csv`,
which is a better way of reading csv files than R's standard
`read.csv`. This was originally developed to make reading csv files faster
and remove some inconsistencies such as string variables being automatically
converted to `factor` (this particular behaviour has now been changed in base
R version 4.0.0 onwards to match tidyverse).

Let's now use the tidyverse to `read_csv` the cats data set
into a `tibble`.

```R
cats <- read_csv("https://chryswoods.com/intermediate_r/data/cats.csv")
```

The first thing you will notice is that the tidyverse has printed
out some useful information;

```
Parsed with column specification:
cols(
  Sex = col_character(),
  BodyWeight = col_double(),
  HeartWeight = col_double()
)
```

This is telling you that `read_csv` found three columns; `Sex`, which 
is treated as a columns of strings (characters), and 
`BodyWeight` and `HeartWeight`, which are both treated as columns
of floating point numbers (doubles).

Next, if you type `cats` and press return...

```R
cats
# A tibble: 144 x 3
   Sex   BodyWeight HeartWeight
   <chr>      <dbl>       <dbl>
 1 F            2           7  
 2 F            2           7.4
 3 F            2           9.5
 4 F            2.1         7.2
 5 F            2.1         7.3
 6 F            2.1         7.6
 7 F            2.1         8.1
 8 F            2.1         8.2
 9 F            2.1         8.3
10 F            2.1         8.5
# … with 134 more rows
```

You can see that the `tibble` summarises itself to the screen. 
This makes it much easier to quickly look at some data without 
it overflowing your console.

As a `tibble` is a `data.frame`, you can use the same methods
of accessing data, e.g.

```R
cats$Bodyweight
```

```
[1] 2.0 2.0 2.0 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.2
 [14] 2.2 2.2 2.2 2.2 2.2 2.3 2.3 2.3 2.3 2.3 2.3 2.3 2.3
 [27] 2.3 2.3 2.3 2.3 2.4 2.4 2.4 2.4 2.5 2.5 2.6 2.6 2.6
 [40] 2.7 2.7 2.7 2.9 2.9 2.9 3.0 3.0 2.0 2.0 2.1 2.2 2.2
 [53] 2.2 2.2 2.2 2.2 2.2 2.2 2.3 2.4 2.4 2.4 2.4 2.4 2.5
 [66] 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.6 2.6 2.6 2.6 2.6 2.6
 [79] 2.7 2.7 2.7 2.7 2.7 2.7 2.7 2.7 2.7 2.8 2.8 2.8 2.8
 [92] 2.8 2.8 2.8 2.9 2.9 2.9 2.9 2.9 3.0 3.0 3.0 3.0 3.0
[105] 3.0 3.0 3.0 3.0 3.1 3.1 3.1 3.1 3.1 3.1 3.2 3.2 3.2
[118] 3.2 3.2 3.2 3.3 3.3 3.3 3.3 3.3 3.4 3.4 3.4 3.4 3.4
[131] 3.5 3.5 3.5 3.5 3.5 3.6 3.6 3.6 3.6 3.7 3.8 3.8 3.9
[144] 3.9
```

```R
cats[1, ]
```

```
# A tibble: 1 x 3
  Sex   BodyWeight HeartWeight
  <chr>      <dbl>       <dbl>
1 F              2           7
```

etc.

In addition to these the `dplyr` tidyverse package provides a number of extra
access methods for data retrieval which we will cover in the next module.

> EXERCISE
>
> Load the cats data set into a `tibble` using `read_csv`.
> Use the `calculate_mean` and `calculate_max` functions
> from before to calculate the mean and max body weight
> and heart weight of the cats.
>
> What are the units for the weights? A description of the
> data set can be found by typing:
>
> ?MASS::cats
>
> [Answer](tidyverse_answer02.html)

## Further reading

* [R for Data Science - Tibbles](https://r4ds.had.co.nz/tibbles.html)
* [R for Data Science - Data Import](https://r4ds.had.co.nz/data-import.html)

## [Previous](dataframes.html) | [Next](magrittr.html)
